version: '3'
services:
  hass:
    image: homeassistant/home-assistant:0.81.2
    ports:
      - "8123:8123"
    volumes:
      - ./compose/ha-config:/config
    environment:
      - TZ=Europe/Berlin
    container_name: "hass"

  appdaemon:
    build:
      context: "."
    links:
      - hass
    volumes:
      - ./compose/apps:/apps
    environment:
      - TZ=Europe/Berlin
      - HA_URL=http://hass:8123
      - HA_KEY=welcome
    container_name: "appdaemon"