version: '3'
services:
  hass:
    image: homeassistant/home-assistant:0.88.2
    ports:
      - "8123:8123"
    volumes:
      - ./compose/ha-config:/config
    environment:
      - TZ=Europe/Berlin
    container_name: "hass"

  appdaemon:
    image: hazard/appdaemon-apps:latest
    links:
      - hass
    volumes:
      - ./compose/apps:/apps
    environment:
      - TZ=Europe/Berlin
      - HA_URL=http://hass:8123
      - HA_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI1ZjEzZTZkNDMwNmE0ZmUwODJmOTI4OTRmMzc5YTI2ZiIsImlhdCI6MTU0NTg5NTAwOCwiZXhwIjoxODYxMjU1MDA4fQ.RdSg11mDT1PNIlA72K-01DKPRCCFnuroj-C2AwehI4E
    container_name: "appdaemon"